JBSH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls')),
    path('permission/', include('permission.urls')),
    # path('account/', include('account.urls')),
]

permission/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = "permission"
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('create/', views.create, name='create')
]

portal/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.index, name="index"),
    path('change_pw/',  views.change_pw, name='change_pw'),
    path('logout/', views.out, name="logout"),
]

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    permitted_place = models.IntegerField(default=0)
    is_advisor = models.BooleanField(default=False)
    period_1 = models.BooleanField(default=False)
    period_2 = models.BooleanField(default=False)

    def _id(self):
        return self.username
    pass

portal/forms.py
from django.contrib.auth.forms import PasswordChangeForm

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })

portal/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.utils import timezone

from .forms import CustomPasswordChangeForm
from .models import User


# Create your views here.
def index(request):    
    response = render(request, "portal/index.html")
    if request.COOKIES.get('user') is not None:
        try:
            # user = User.objects.get(username=request.COOKIES.get('user'))
            # print(user)
            username = user.get("username")
            password = user.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return response
            else:
                return response
        except:
            response.delete_cookie('user')
            return response

    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            user_instance = User.objects.get(username=username)
            response.set_cookie('user', user_instance)
            return redirect('portal:index')
        else:
            return render(request, 'portal/index.html', {'error':'다시 입력해주세요.'})
    
    else:
        return render(request, "portal/index.html")
    

@login_required
def out(request):
    response = redirect('portal:index')
    response.delete_cookie('user')
    logout(request)
    return response

@login_required
def change_pw(request):
    context = {}
    if request.method == "POST":
        form = CustomPasswordChangeForm(request.user, request.POST)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('portal:change_pw')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'portal/change_pw.html', {'form':form})

portal/templates/portal/change_pw.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="nav-bar">
        {% if user.is_authenticated %}
        <div id="studentID">
            <p>{{user.username}}{{user.last_name}}{{user.first_name}}</p>
        </div>
        {% endif %}
        <a href="{% url 'portal:index' %}" >메인화면으로</a>
    </div>
    <p>비밀번호가 변경되어도 메시지가 나타나지 않습니다.</p>
    <form method="POST" novalidate>
    {% csrf_token %}
    <div>
        <label name="label_old_password" for="{{ form.old_password.id_for_label }}">{{ form.old_password.label }}</label>
        {{ form.old_password }}
        <script type="text/javascript">
            if (document.getElementsByName('old_password')[0].value != '') {
                document.getElementsByName('label_old_password')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.old_password.errors %}
        <script type="text/javascript">
            document.getElementsByName('old_password')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.old_password.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <label name="label_new_password1" for="{{ form.new_password1.id_for_label }}">{{ form.new_password1.label }}</label>
        {{ form.new_password1 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password1')[0].value != '') {
                document.getElementsByName('label_new_password1')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.new_password1.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password1')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.new_password1.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <label name="label_new_password2" for="{{ form.new_password2.id_for_label }}">{{ form.new_password2.label }}</label>
        {{ form.new_password2 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password2')[0].value != '') {
                document.getElementsByName('label_new_password2')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.new_password2.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password2')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.new_password2.errors %}
        <div style="white-space: nowrap;" class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
        <small>
            최소 8개의 숫자와 문자 또는 특수기호를 입력해주세요.
        </small>
    </div>
    <button type="submit" class="btn btn-login">비밀번호 변경</button>
</form>
</body>
</html>

portal/templates/portal/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="nav-bar" class="nav-bar">
        {% if user.is_authenticated %}
            <div class="nav-name">
                <p>{{user.username}}{{user.last_name}}{{user.first_name}}</p>
            </div>
            <a href="{% url 'portal:change_pw' %}">비밀번호 변경</a>
            <a href="{% url 'portal:logout' %}">로그아웃</a>
        {% else %}
        <form method="post">
        <form method="post">
            {% csrf_token %}
            <div class="input-login">
                <label for="username">학번</label>
                <input type="text" id="username" name="username" required  value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="input-login">
                <label for="password">비밀번호</label>
                <input type="password" id="password" name="password" required value="{{ form.password.value|default_if_none:'' }}">
            </div>
            {% if error %}
            <div class="err_message">
                <p>{{error}}</p>
            </div>
            {% endif %}
            <button type="submit" class="btn btn-login">로그인</button>
        </form> 
        {% endif %}
    </div>
    <p>O HAI!</p>
    <div>
        <a href="{% url 'permission:index' %}">허가원</a>
    </div>
</body>
</html>