JBSH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls')),
    path('permission/', include('permission.urls')),
    # path('account/', include('account.urls')),
]

permission/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = "permission"
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('create/', views.create, name='create')
]

portal/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.index, name="index"),
    path('change_pw/',  views.change_pw, name='change_pw'),
    path('logout/', views.out, name="logout"),
]

permission/models.py
from django.db import models
import datetime

# Create your models here.
class Permission(models.Model):
    activity = models.CharField(max_length=10)
    activity_detail = models.CharField(max_length=2, default='')
    participants = models.JSONField()
    place = models.IntegerField(default=0)
    pub_date = models.DateField(default=datetime.date.today)
    period_1 = models.BooleanField(default=False)
    period_2 = models.BooleanField(default=False)
    is_permitted = models.BooleanField(default=False)
    representative =  models.IntegerField()
    advisor = models.CharField(max_length=35)

class Place(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=10)
    headcount = models.IntegerField(default=0)

permission/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

import json

from .models import Permission, Place

# Create your views here.
def index(request):
    permission_list = Permission.objects.all()
    return render(request, 'permission/index.html', {'permission_list':permission_list})
    
def detail(request):
    return render(request, 'permission/details.html')

@login_required
def create(request):
    if request.method == "POST":
        """
        activity = models.CharField(max_length=10)
        activity_detail = models.CharField(max_length=2, default='')
        participants = models.JSONField()
        place = models.IntegerField(default=0)
        pub_date = models.DateField(default=datetime.date.today)
        period_1 = models.BooleanField(default=False)
        period_2 = models.BooleanField(default=False)
        is_permitted = models.BooleanField(default=False)
        representative =  models.IntegerField()
        advisor = models.CharField(max_length=35)
        """
        try:
            request.POST['period_1']
            period_1 = True
        except:
            period_1 = False
        
        try:
            request.POST['period_2']
            period_2 = True
        except:
            period_2 = False

        representative = request.POST['representative'] if request.POST['representative'] else int(request.user.username)

        p = Permission(
            activity = request.POST['activity'],
            activity_detail = request.POST['activity_detail'],
            participants = json.dumps({'participants':request.POST['participants']}),
            place = request.POST['place'],
            period_1 = period_1,
            period_2 = period_2,
            representative = representative,
            advisor = request.POST['advisor'],
        )
        p.save()
        return redirect('permission:index')
    else:
        return render(request, 'permission/create.html', {'place_list': Place.objects.all()})

permission/templates/permission/change_pw.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" novalidate>
    {% csrf_token %}
    <div>
        <label name="label_old_password" for="{{ form.old_password.id_for_label }}">{{ form.old_password.label }}</label>
        {{ form.old_password }}
        <script type="text/javascript">
            if (document.getElementsByName('old_password')[0].value != '') {
                document.getElementsByName('label_old_password')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.old_password.errors %}
        <script type="text/javascript">
            document.getElementsByName('old_password')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.old_password.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <label name="label_new_password1" for="{{ form.new_password1.id_for_label }}">{{ form.new_password1.label }}</label>
        {{ form.new_password1 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password1')[0].value != '') {
                document.getElementsByName('label_new_password1')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.new_password1.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password1')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.new_password1.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <label name="label_new_password2" for="{{ form.new_password2.id_for_label }}">{{ form.new_password2.label }}</label>
        {{ form.new_password2 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password2')[0].value != '') {
                document.getElementsByName('label_new_password2')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.new_password2.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password2')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.new_password2.errors %}
        <div style="white-space: nowrap;" class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
        <small>
            최소 8개의 숫자와 문자 또는 특수기호를 입력해주세요.
        </small>
        <button type="submit" class="btn btn-login">비밀번호 변경</button>
    </div>
    <a href="{% url 'permission:index' %}">메인화면으로</a>
</form>
</body>
</html>

permission/templates/permission/create.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="nav-bar">
        {% if user.is_authenticated %}
        <div id="studentID">
            <p>{{user.username}}{{user.last_name}}{{user.first_name}}</p>
        </div>
        {% endif %}
        <a href="{% url 'permission:index' %}" >허가원으로</a>
        <a href="{% url 'portal:index' %}" >메인화면으로</a>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label name="label_activity" for="activity">활동명(10자 이내)</label>
            <input name="activity" type="text" required/>
        </div>
        <div>
            <label name="label_activity_detail" for="activity_detail">활동내용(20자 이내)</label>
            <input name="activity_detail" type="text" required/>
        </div>
        <div>
            <label name="label_place" for="place">장소</label>
            <div id="place-picker">
                {% for place in place_list %}
                <div class="place-radio">
                    <input name="place" type="radio" value={{place.id}}>
                    <label name="label_place" for="place">[{{place.id}}]{{place.name}}</label>
                </div>
                {% endfor %}
            </div>
        </div>
        <div>
            <label name="label_participants" for="participants">참가자</label>
            <input name="participants" type="text"/>
        </div>
        <div>
            <label name="label_period_1" for="period_1">1교시</label>
            <input name="period_1" type="checkbox" />
        </div>
        <div>
            <label name="label_period_2" for="period_2">2교시</label>
            <input name="period_2" type="checkbox"/>
        </div>
        <div>
            <label name="label_representative" for="representative">대표자 학번(미입력시 개설자)</label>
            <input name="representative" type="text"/>
        </div>
        <div>
            <label name="label_advisor" for="advisor">지도교사</label>
            <input required name="advisor" type="text" required/>
        </div>
        <button type="submit" class="btn btn-login">허가원 개설</button>
    </form>
</body>
</html>

permission/templates/permission/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'permission/style.css' %}">
</head>
<body>
    <div class="grid-container">
        <div id="nav-bar">
            <a href="{% url 'portal:index' %}" ><span>메인화면으로</span></a>
            {% if user.is_authenticated %}
            <a href="{% url 'permission:create' %}"><span>허가원 개설하기</span></a>
            <span id="studentID">
                {{user.username}}<!--{{user.last_name}}{{user.first_name}}-->
            </span>
            {% endif %}  
        </div>
        <table class="table-center">
            <tr>
                <th class="center index-cell">활동명</th>
                <th class="center index-cell">대표자</th>
                <th class="center index-cell">교실</th>
                <th class="center index-cell">허가 여부</th>
            </tr>
            {% for content in permission_list %}
            <!--<a href="{% url 'permission:detail'  %}" >-->
                <tr>
                    <td class="center index-cell">{{content.activity}}</td>
                    <td class="center index-cell">{{content.representative}}</td>
                    <td class="center index-cell">{{content.place}}</td>
                    <td class="center index-cell">
                        {% if content.is_permitted %}
                            <img src="{% static 'permission/img/accept.png' %}" class="accepted" alt="accepted" width="10" height="10">
                        {% else %}
                            <img src="{% static 'permission/img/rec.png' %}" class="accepted" alt="not accepted" width="10" height="10">
                        {% endif %}
                    </td>
                </tr>
            <!--</a>-->
            {% endfor %}
        </table>
        <div id="footer">
            <a href="https://www.flaticon.com/free-icons/rec" title="rec icons">Rec icons created by Freepik - Flaticon</a>
            <a href="https://www.flaticon.com/free-icons/correct" title="correct icons">Correct icons created by Aldo Cervantes - Flaticon</a>
        </div>
    </div>

</body>
</html>

permission/templates/permission/ohai.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>